#!/bin/bash

cd /Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution
tmpDir=$(mkdir -p "/Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/tmp.3e5fd1e0" && echo "/Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/tmp.3e5fd1e0")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution

)
out09a25880="${tmpDir}/out.$$" err09a25880="${tmpDir}/err.$$"
mkfifo "$out09a25880" "$err09a25880"
trap 'rm "$out09a25880" "$err09a25880"' EXIT
tee '/Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution/stdout' < "$out09a25880" &
tee '/Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution/stderr' < "$err09a25880" >&2 &
(
cd /Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution


echo 'Hello World!'
)  > "$out09a25880" 2> "$err09a25880"
echo $? > /Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution
sync


)
mv /Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution/rc.tmp /Users/zainraza/Downloads/dev/miscell/tutorials_and_random/Cromwell/cromwell-executions/test/09a25880-1fb0-4e59-aaf7-d8e1c977e274/call-hello/execution/rc
